document.title ="GoogleForm";
document.body.style.background= "brown";
const a=document.createElement("h1");
a.textContent="Personal Information";
sai.appendChild(a);
const c=document.createElement("label");
const b=document.createElement("input");
c.textContent="Enter Name:";
b.type="text";
b.placeholder="Enter your full name";
sai.appendChild(c);
sai.appendChild(document.createElement("br"));
sai.appendChild(b);
sai.appendChild(document.createElement("br"));
sai.appendChild(document.createElement("br"));
const name=document.createElement("label");
const name1=document.createElement("input");
name.textContent="Enter Rollno:";
name1.type="text";
name1.placeholder="Enter your rollno";
sai.appendChild(name);
sai.appendChild(document.createElement("br"));
sai.appendChild(name1);
sai.appendChild(document.createElement("br"));
sai.appendChild(document.createElement("br"));
const l=document.createElement("label");
l.textContent="Gender:";
sai.appendChild(l);
const z=document.createElement("label");
const z1=document.createElement("input");
z.textContent="Male";
z1.name="name";
z1.type="radio";
sai.appendChild(z);
sai.appendChild(z1);
const x=document.createElement("label");
const x1=document.createElement("input");
x.textContent="Female";
x1.name="name";
x1.type="radio";
sai.appendChild(x);
sai.appendChild(x1);
sai.appendChild(document.createElement("br"));
sai.appendChild(document.createElement("br"));
const j=document.createElement("label");
const j1=document.createElement("input");
j.textContent="Father name:";
j1.type="text";
j1.placeholder="Enter your father name";
sai.appendChild(j);
sai.appendChild(document.createElement("br"));
sai.appendChild(j1);
sai.appendChild(document.createElement("br"));
sai.appendChild(document.createElement("br"));
const k=document.createElement("label");
const k1=document.createElement("input");
k.textContent="Mother name:";
k1.type="text";
k1.placeholder="Enter your mother name";
sai.appendChild(k);
sai.appendChild(document.createElement("br"));
sai.appendChild(k1);
sai.appendChild(document.createElement("br"));
sai.appendChild(document.createElement("br"));
const nam=document.createElement("label");
const nam1=document.createElement("input");
nam.textContent="Enter Email:";
nam1.type="text";
nam1.placeholder="Enter your email";
sai.appendChild(nam);
sai.appendChild(document.createElement("br"));
sai.appendChild(nam1);
sai.appendChild(document.createElement("br"));
sai.appendChild(document.createElement("br"));
const na=document.createElement("label");
const na1=document.createElement("input");
na.textContent="Confirm Email:";
na1.type="text";
na1.placeholder="Confirm your email";
sai.appendChild(na);
sai.appendChild(document.createElement("br"));
sai.appendChild(na1);
sai.appendChild(document.createElement("br"));
sai.appendChild(document.createElement("br"));
const n=document.createElement("label");
const n1=document.createElement("input");
n.textContent="Phone number:";
n1.type="text";
n1.placeholder="Enter your phone number";
sai.appendChild(n);
sai.appendChild(document.createElement("br"));
sai.appendChild(n1);
sai.appendChild(document.createElement("br"));
sai.appendChild(document.createElement("br"));
const s=document.createElement("label");
const s1=document.createElement("textarea");
s.textContent="Address:";
s1.type="text";
s1.placeholder="Enter your address";
sai.appendChild(s);
sai.appendChild(document.createElement("br"));
sai.appendChild(s1);
sai.appendChild(document.createElement("br"));
sai.appendChild(document.createElement("br"));
const f=document.createElement("label");
const f1=document.createElement("input");
f.textContent="Password:";
f1.type="text";
f1.placeholder="Enter your password";
sai.appendChild(f);
sai.appendChild(document.createElement("br"));
sai.appendChild(f1);
sai.appendChild(document.createElement("br"));
sai.appendChild(document.createElement("br"));
const e=document.createElement("label");
const e1=document.createElement("input");
e.textContent="Confirm Password:";
e1.type="text";
e1.placeholder="Confirm your password";
sai.appendChild(e);
sai.appendChild(document.createElement("br"));
sai.appendChild(e1);
sai.appendChild(document.createElement("br"));
sai.appendChild(document.createElement("br"));
const h=document.createElement("label");
const h1=document.createElement("textarea");
h.textContent="Comments:";
h1.type="text";
h1.placeholder="Enter your Comments";
sai.appendChild(h);
sai.appendChild(document.createElement("br"));
sai.appendChild(h1);
sai.appendChild(document.createElement("br"));
sai.appendChild(document.createElement("br"));
const g=document.createElement("button");
g.textContent="Submit";
sai.appendChild(g);
